In [1]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x1d2141a3880>)

In [2]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    else:
        return torch.device('cpu')


def try_all_gpus():
    devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]


try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [3]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [4]:
x = torch.ones(2, 3, device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [5]:
y = torch.ones(2, 3, device=try_gpu(1))
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
z = y.cuda(0)  #拷贝到gpu上
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [10]:
net=nn.Sequential(nn.Linear(3,1))
net=net.to(device=try_gpu())
net(x)

tensor([[0.2943],
        [0.2943]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [11]:
net[0].weight.data.device

device(type='cuda', index=0)